on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  publish-website:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup R
        uses: r-lib/actions/setup-r@v1
      
      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v1
      
      - name: Setup TinyTex
        uses: r-lib/actions/setup-tinytex@v1
      
      - name: Install rmarkdown
        run: Rscript -e 'install.packages("rmarkdown")'

      - name: Render rmarkdown notebook
        run: Rscript -e 'rmarkdown::render("Notebook.Rmd")'

      - name: Rename html
        run: mv Notebook.html index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
